# .circleci/config.yml
version: 2
jobs:
  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate Dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - deps-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all
          command: cargo build --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: dep-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all
